# MySQL
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/webty_db
    username: webty_user
    password: webty
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
